### PR TITLE
Patch for an issue which made it not possible to properly unmount a Unity instance

### PR DESCRIPTION
**Pull request by jeffreylanters**
This pull request includes a patch for the famous problem #22 where a Unity Instance cannot be unmounted. This is simple due to Unity not letting me do so. In the newest unity `version 2019.1`, the ability to as they call `Quit` the WebGL application was added to unload the player from the memory.

Note that this will be only available on Unity 2019.1 or newer, and needs to be tested heavily before I'll publicly release this patch.

### CODE REVIEW

**Comment by MuhammadFaizanKhan** [comment]
Whats your suggestion is this working fine? remember Unity 2019.1 is in beta format so we can't use it production right now so problem will remain the same.

**Comment by jeffreylanters** [comment]
@MuhammadFaizanKhan #22 Yes, Unity 2019.1 is still in beta. Still I'm looking for any beta testers to this this feature so I could release it in time with the release of Unity 2019.

**Comment by MuhammadFaizanKhan** [comment]
> 
> 
> @MuhammadFaizanKhan #22 Yes, Unity 2019.1 is still in beta. Still I'm looking for any beta testers to this this feature so I could release it in time with the release of Unity 2019.

Best of luck for future endeavors but a clarification require that the problem will remain same with old unity version?

**Comment by jeffreylanters** [comment]
@MuhammadFaizanKhan Thanks. And yes, that's simply because Unity doesn't allow unloading the player from the memory in versions below 2019.1.

**Comment by MuhammadFaizanKhan** [comment]
> 
> 
> @MuhammadFaizanKhan Thanks. And yes, that's simply because Unity doesn't allow unloading the player from the memory in versions below 2019.1.

Yes, Maybe this is the reason when you do page reload, the chrome increment the memory. There is a memory leak issue which is serious concern.  I don't know that firefox also behaving in the same way.

**Comment by MuhammadFaizanKhan** [comment]
> @MuhammadFaizanKhan Thanks. And yes, that's simply because Unity doesn't allow unloading the player from the memory in versions below 2019.1.

I found that when the dev tools are open and you are measuring the memory then, chrome is keep increment the memory. So it basically related to dev tools of chrome.

**Pull request merged**
